# fly.toml app configuration file generated for peter-garas-datebook on 2023-07-03T15:46:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "peter-garas-datebook"
primary_region = "mia"

[build]
  image = "petergaras/datebook:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dpfq5kdop"
  CloudinarySettings__ApiKey="897863945719687"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
